
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JPanel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author ManuelSotoBaquero
 */
public class Secundaria extends javax.swing.JDialog {

    /**
     * Creates new form Secundaria
     */
    public Secundaria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        jPanelSecundario.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNavPpal = new javax.swing.JButton();
        jLabelResultado = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelPatron = new javax.swing.JLabel();
        jPanelPrimario = new javax.swing.JPanel();
        jLabelPrimario = new javax.swing.JLabel();
        jLabelValorPrimario = new javax.swing.JLabel();
        jLabelDescPrimario = new javax.swing.JLabel();
        jPanelSecundario = new javax.swing.JPanel();
        jLabelSecundario = new javax.swing.JLabel();
        jLabelValorSecundario = new javax.swing.JLabel();
        jLabelDescSecundario = new javax.swing.JLabel();
        jLabelValorPatron = new javax.swing.JLabel();
        jLabelDescPatron = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Resultado método DISC");
        setMaximumSize(null);
        setPreferredSize(null);

        jButtonNavPpal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonNavPpal.setText("Realizar test");
        jButtonNavPpal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNavPpalActionPerformed(evt);
            }
        });

        jLabelResultado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelResultado.setText("RESULTADO TEST MÉTODO DISC");

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabelPatron.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPatron.setText("Patrón:");

        jPanelPrimario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelPrimario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPrimario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrimario.setText("Perfil primario: ");

        jLabelValorPrimario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelValorPrimario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelValorPrimario.setText("jLabel4");

        jLabelDescPrimario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDescPrimario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescPrimario.setText("jLabelDescPrimario");

        javax.swing.GroupLayout jPanelPrimarioLayout = new javax.swing.GroupLayout(jPanelPrimario);
        jPanelPrimario.setLayout(jPanelPrimarioLayout);
        jPanelPrimarioLayout.setHorizontalGroup(
            jPanelPrimarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrimarioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelPrimarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrimarioLayout.createSequentialGroup()
                        .addComponent(jLabelDescPrimario, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(jPanelPrimarioLayout.createSequentialGroup()
                        .addComponent(jLabelPrimario)
                        .addGap(29, 29, 29)
                        .addComponent(jLabelValorPrimario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelPrimarioLayout.setVerticalGroup(
            jPanelPrimarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrimarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrimarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrimario)
                    .addComponent(jLabelValorPrimario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDescPrimario, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelSecundario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelSecundario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelSecundario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSecundario.setText("Perfil secundario:");

        jLabelValorSecundario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelValorSecundario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelValorSecundario.setText("jLabel5");

        jLabelDescSecundario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDescSecundario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescSecundario.setText("jLabelDescSecundario");
        jLabelDescSecundario.setToolTipText("");

        javax.swing.GroupLayout jPanelSecundarioLayout = new javax.swing.GroupLayout(jPanelSecundario);
        jPanelSecundario.setLayout(jPanelSecundarioLayout);
        jPanelSecundarioLayout.setHorizontalGroup(
            jPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSecundarioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSecundarioLayout.createSequentialGroup()
                        .addComponent(jLabelDescSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(jPanelSecundarioLayout.createSequentialGroup()
                        .addComponent(jLabelSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelValorSecundario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelSecundarioLayout.setVerticalGroup(
            jPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSecundarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSecundario)
                    .addComponent(jLabelValorSecundario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDescSecundario, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabelValorPatron.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelValorPatron.setText("jLabel6");

        jLabelDescPatron.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDescPatron.setText("jLabelDescPatron");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDescPatron, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelPatron, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelValorPatron, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jPanelPrimario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanelPrimario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelSecundario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPatron)
                    .addComponent(jLabelValorPatron))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDescPatron, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 93, Short.MAX_VALUE)
                .addComponent(jLabelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jButtonNavPpal, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelResultado)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonNavPpal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNavPpalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNavPpalActionPerformed
        Principal principal = new Principal();
        principal.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNavPpalActionPerformed
   
    // función para cambiar los textos de las etiquetas (que son privadas) desde
    // la pantalla principal
    public void actualiza_valor(String etiqueta, String texto, int valor){
        Color color = Color.GRAY;
        Color colortxt = Color.BLACK;
        String txt = "Ninguno";
        String desc = "Descripción";
        String porcentaje = String.valueOf(valor*5);
       
        
        switch (texto){
            case "D":
                txt = "Dominante";
                color = Color.RED;
            break;
            case "I":
                txt = "Influyente";
                color = Color.blue;
            break;

            case "S":
                txt = "Solido";
                color = Color.GREEN;
            break;
            
            case "C":
                txt = "Controlador";
                color = Color.YELLOW;
                
               break;
            
           
            default:
                txt = "Ninguno";
            break;    
        }
        txt = txt + " ("+ porcentaje +"%)";
        switch (etiqueta){
            case "primario":       
            jLabelValorPrimario.setText(txt);
            if (texto == "C" || texto == "S"){
                jLabelValorPrimario.setForeground(colortxt);
                jLabelPrimario.setForeground(colortxt);
                jLabelDescPrimario.setForeground(colortxt);
            }
            jPanelPrimario.setBackground(color);
            jLabelDescPrimario.setText(desc);
            
            break;
        
            case "secundario":
            jLabelValorSecundario.setText(txt);
            jPanelSecundario.setBackground(color);
            jLabelDescSecundario.setText(desc);
            if (texto == "C" || texto == "S"){
                jLabelValorSecundario.setForeground(colortxt);
                jLabelSecundario.setForeground(colortxt);
                jLabelDescSecundario.setForeground(colortxt);
            }
            if (!porcentaje.equals("0")){
                jPanelSecundario.setVisible(true);
            }
            
            break;
            case "patron":
            jLabelValorPatron.setText(texto);
            jLabelDescPatron.setText(desc);
            break;
        
        }
        
        
    }
    
    private String calcula_desc(String txt){
        String desc =" ";
        switch (txt){
            case "D":
                desc = "<html><p>Personas decididas, rápidas, continuamente en pos de resultados concretos. "
                        + "En sus excesos los D pueden mostrarse prepotentes, poco considerados de "
                        + "los sentimientos ajenos y escasamente cuidadosos de los detalles.</p></html>";
                break;
            case "I":
                desc = "<html><p>Personas comunicativas, que dan importancia a los sentimientos, de buen humor, "
                        + "inclinadas a establecer amplias relaciones sociales. En sus excesos los I "
                        + "pueden mostrarse muy habladores, desorganizados e irascibles.</p></html>";
                break;
            case "S":
                desc = "<html><p>Personas tranquilas, serviciales y solidarias, preocupadas por mantener un entorno "
                        + "seguro, sin cambios abruptos. En sus excesos los S pueden resultar apegados al "
                        + "pasado, dubitativos y temerosos</p></html>";
                break;
            case "C":
                desc = "<html><p>Personas racionales, rigurosas, legalistas, interesadas en controlar en detalle la "
                        + "corrección de los procedimientos. En sus excesos los C pueden ser ritualistas, "
                        + "pedantes y quedar paralizados por ansias de perfeccionismo.</p></html>";
                break;
            case "Emprendedor":
                desc = "Eficiencia - Independencia - Automotivación";
                break;
            case "Promotor":
                desc = "Amigable - Entusiasmo - Autoconfianza";
                break;
            case "Planificador":
                desc = "Paciencia - Reflexividad - Perseverancia";
                break;
            case "Pensador, Analista":
                desc = "Cooperatividad - Precisión - Sensibilidad";
                break;
            case "Competidor":
                desc = "Automotivación - Independencia - Entusiasmo";
                break;
            case "Perfil poco común":
                desc = "<html><p>Eficiencia - Independencia - Reflexividad - Perseverancia</p></html>";
                break;
            case "Creativo":
                desc = "<html><p>Eficiencia - Automotivación - Precisión - Sensibilidad</p></html>";
                break;
            case "Perfil valioso":
                desc = "Independencia - Autoconfianza - Perseverancia";
                break;
            case "Dinámico":
                desc = "Automotivación - Entusiasmo - Sensibilidad";
                break;
            case "Analista competitivo":
                desc = "Eficiencia - Reflexividad - Precisión";
                break;
            case "Consejero":
                desc = "<html><p>Amigable - Autoconfianza - Paciencia - Perseverancia</p></html>";
                break;
            case "Evaluador":
                desc = "<html><p>Amigable - Entusiasmo - Cooperatividad - Sensibilidad</p></html>";
                break;
            case "Experto, Profesional":
                desc = "Amigable - Paciencia - Cooperatividad";
                break;
            case "Perfeccionista":
                desc = "<html><p>Paciencia - Reflexividad - Cooperatividad - Precisión</p></html>";
                break;
            case "Ninguno":
                desc = "";
                break;
        }
        
        return desc;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Secundaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Secundaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Secundaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Secundaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Secundaria dialog = new Secundaria(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNavPpal;
    private javax.swing.JLabel jLabelDescPatron;
    private javax.swing.JLabel jLabelDescPrimario;
    private javax.swing.JLabel jLabelDescSecundario;
    private javax.swing.JLabel jLabelPatron;
    private javax.swing.JLabel jLabelPrimario;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JLabel jLabelSecundario;
    private javax.swing.JLabel jLabelValorPatron;
    private javax.swing.JLabel jLabelValorPrimario;
    private javax.swing.JLabel jLabelValorSecundario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelPrimario;
    private javax.swing.JPanel jPanelSecundario;
    // End of variables declaration//GEN-END:variables
}
